import "./globals.css";
import { Metadata } from "next";
import Header from "@/components/Header";


export const metadata: Metadata = {
  title: "Grocery store App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
